export { default as getOne } from './getOne'
export { default as getMany } from './getMany'
export { default as postAny } from './postAny'
export { default as patchOne } from './patchOne'
export { default as defaultRoutes } from './defaultRoutes'
export { KoaModel } from './types'
